INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Fly me to the moon', 'travel', 30000, "11-2-2018", '12-2-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Aruba, Jamaica, I want to take ya', 'travel', 7000, "11-2-2018", '12-2-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Fly like a G6', 'travel', 70000, "11-2-2018", '12-2-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Read Around the World', 'education', 25000, "1-2-2018", '2-2-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Reading Rainbow', 'education', 200, "4-5-2018", '12-2-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Monsters Inc', 'charity', 1000, "8-2-2018", '5-2-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Halloweenie Fund', 'charity', 500, "6-2-2018", '12-2-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Roasted Marshmallow Fundraiser", 'charity', 25, "11-2-2018", '12-2-2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Spin Doctor Concert", 'music', 100, "7-2-2018", '10-2-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Last Hurrah", 'charity', 100000, "11-2-2018", '12-2-2018');
--
INSERT INTO users (name, age) VALUES ('Samantha', 32);
INSERT INTO users (name, age) VALUES ('Anurag', 39);
INSERT INTO users (name, age) VALUES ('Brette', 36);
INSERT INTO users (name, age) VALUES ('Lily', 4);
INSERT INTO users (name, age) VALUES ('Amelia', 5);
INSERT INTO users (name, age) VALUES ('Sebastian', 2);
INSERT INTO users (name, age) VALUES ('Ancy', 36);
INSERT INTO users (name, age) VALUES ('Christina', 27);
INSERT INTO users (name, age) VALUES ('Maura', 31);
INSERT INTO users (name, age) VALUES ('Beatrice', 32);
INSERT INTO users (name, age) VALUES ('Hai', 34);
INSERT INTO users (name, age) VALUES ('Kristen', 25);
INSERT INTO users (name, age) VALUES ('David', 6);
INSERT INTO users (name, age) VALUES ('Abid', 36);
INSERT INTO users (name, age) VALUES ('Greg', 37);
INSERT INTO users (name, age) VALUES ('Ron', 32);
INSERT INTO users (name, age) VALUES ('Mary', 67);
INSERT INTO users (name, age) VALUES ('Lindsey', 34);
INSERT INTO users (name, age) VALUES ('Natalee', 18);
INSERT INTO users (name, age) VALUES ('Mary Lane', 74);
-- -- --
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (876, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (457, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (456, 10, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (654, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (987, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (54, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (876, 20, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (356, 18, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3076, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (876, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3457, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (356, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4567, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (78, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (79, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (887, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (43, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (667, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 13, 6);
